service: viz-huc-processing
provider:
  name: aws
  deploymentBucket: 
    name: ${env:DEPLOYMENT_BUCKET}
    serverSideEncryption: AES256
  region: ${env:AWS_DEFAULT_REGION}
functions:
  lambda:
    name: ${env:LAMBDA_NAME}
    image: ${env:AWS_ACCOUNT_ID}.dkr.ecr.${env:AWS_DEFAULT_REGION}.amazonaws.com/${env:IMAGE_REPO_NAME}:${env:IMAGE_TAG}
    role: ${env:LAMBDA_ROLE_ARN}
    memorySize: 3072
    timeout: 900
    ephemeralStorageSize: 1024
    environment:
      FIM_BUCKET: ${env:FIM_BUCKET}
      FIM_PREFIX: ${env:FIM_PREFIX}
      VIZ_DB_DATABASE: ${env:VIZ_DB_DATABASE}
      VIZ_DB_HOST: ${env:VIZ_DB_HOST}
      VIZ_DB_PASSWORD: ${env:VIZ_DB_PASSWORD}
      VIZ_DB_USERNAME: ${env:VIZ_DB_USERNAME}
      EGIS_DB_DATABASE: ${env:EGIS_DB_DATABASE}
      EGIS_DB_HOST: ${env:EGIS_DB_HOST}
      EGIS_DB_PASSWORD: ${env:EGIS_DB_PASSWORD}
      EGIS_DB_USERNAME: ${env:EGIS_DB_USERNAME}
    vpc:
      securityGroupIds:
        - ${env:SECURITY_GROUP_1}
      subnetIds:
        - ${env:SUBNET_1}
        - ${env:SUBNET_2}
